version: "3.9"
services:
  # backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server:/app # overrides /app from COPY in Dockerfile
      - jobapplication_server_node_modules:/app/node_modules # create docker volume

  # frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./client:/app
      - jobapplication_client_node_modules:/app/node_modules

  # qdrant
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - jobapplication_qdrant:/qdrant/storage
      
  # python
  python:
    build:
      context: ./python_app
      dockerfile: Dockerfile
      network: host
    ports:
      - "8080:8080"
    volumes:
      - ./python_app:/app
      - ./python_app/model_cache:/tmp/fastembed_cache
    
volumes:
  jobapplication_qdrant:
    external: true
  jobapplication_server_node_modules:
    external: true
  jobapplication_client_node_modules:
    external: true